name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      UNTILL_MAVEN_USERNAME: Alex
      UNTILL_MAVEN_PASSWORD: Alex
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
